# Generated by Django 3.1.3 on 2020-12-12 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email1', models.EmailField(max_length=254)),
                ('user_email2', models.EmailField(max_length=254)),
                ('user_location', models.CharField(max_length=50)),
                ('user_file', models.FileField(blank=True, upload_to='documents')),
                ('addmin_comment', models.TextField()),
                ('user_replay', models.TextField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('primary', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRegistrationApp.userprofiledetails')),
            ],
        ),
    ]
