# Generated by Django 3.1.3 on 2020-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledetails',
            name='user_role',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
